[workspace]
authors = ["Constantinos Tsakonas <tsakonas.constantinos@gmail.com>"]
channels = ["conda-forge"]
name = "butane"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]

[dependencies]
python = ">=3.12"
scipy = ">=1.17.1,<2"
wandb = ">=0.26.1,<0.27"
imageio = ">=2.37.0,<3"

[pypi-dependencies]
torch = { version = "==2.11.0", index = "https://download.pytorch.org/whl/cu130" }

[feature.test.dependencies]
pytest = "*"
h5py = "*"

[environments]
default = { features = [], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
